import string
from random import randint
from time import sleep
import os
clear = lambda: os.system("cls")
sleep(randint(5, 10) // 2)
print("LoveMeter™ is booting up . . .")
sleep(randint(5, 10) // 2)

print("DEFAULT LANG: SWE")
sleep(randint(1, 10) // 5)
clear()
namn = input("Ditt namn: ")
sleep(randint(2, 3) // 2)
crush = input("Ditt crush namn: ")
sleep(randint(2, 4))
lst = [word[0].upper() + word[1:] for word in namn.split()]
namn = " ".join(lst)

lst = [word[0].upper() + word[1:] for word in crush.split()]
crush = " ".join(lst)

if namn == "Zach" and crush == "Ellie":
    print("\nDetta är resultaren från 10 universum. Vi är nummer", str(randint(1, 10)) + ".")
    sleep(0.5)
    print(" Universum 1: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 2: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 3: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 4: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 5: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 6: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 7: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 8: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 9: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 10: Det är", str(randint(-1000, 10)) + "% chans att", namn, "blir ihop med", crush + ".")
else:
    print("Detta är resultaren från 10 olika universum. Vi är nummer", str(randint(1, 10)) + ".")
    sleep(0.5)
    print(" Universum 1: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 2: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 3: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 4: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 5: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 6: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 7: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 8: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 9: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")
    sleep(0.5)
    print(" Universum 10: Det är", str(randint(0, 100)) + "% chans att", namn, "blir ihop med", crush + ".")

sleep(3)
input("\nTryck på enter för att avsluta :)")
